[build]
  publish = "public"  # Or wherever your static assets are
  command = "npm run build"

[functions]
  directory = "functions"  # This points to your functions folder

  [[functions]]
    name = "update"  # Your function name that Telegram uses
    timeout = 10  # Timeout in seconds (increase if needed)
    memory = 1024  # Allocating 1 GB of memory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
