[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "functions"

[functions.update]
  path = "/api/update"
  timeout = 10
  memory = 1024

[redirects]
  from = "/*"
  to = "/index.html"
  status = 200
