[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "functions"
 node_bundler = "esbuild"

[[functions]]
  function = "telegram-bot"
  path = "/api/telegram-bot"
  node_bundler = "esbuild"
  included_files = ["node_modules/**/*"]

[redirects]
  [[redirects]]
  from = "/*"
  to = "/api/telegram-bot"
  status = 200
